const STR = {
  fr: {
    eyebrow: "Wi‑Fi invité",
    heroTitle: "Achetez un pass internet en quelques secondes.",
    heroLead:
      "Choisissez une offre, une méthode de paiement, puis activez l'accès.",
    stepPick: "Choisir l'offre",
    stepPay: "Valider le paiement",
    stepOn: "Accès activé",
    catalogLead: "Catalogue Wi‑Fi invité avec méthodes de paiement configurées par votre FAI.",
    wifiBannerAria: "Visuel promotionnel opérateur",
    accessTitle: "Accéder à votre FAI",
    accessLead: "Saisissez l'identifiant FAI (UUID) communiqué par votre opérateur.",
    ispPh: "Identifiant FAI (UUID fourni par l'opérateur)",
    showPlans: "Afficher les offres",
    postPayTitle: "Créer votre mot de passe portail",
    postPayHelp:
      "Sur la page portail client, utilisez Première connexion, collez ce jeton, puis définissez un mot de passe pour vous connecter plus tard avec votre téléphone.",
    openPortal: "Ouvrir le portail client",
    continueWifi: "Continuer vers le Wi‑Fi / redirection",
    noPlans: "Aucune offre publique pour le moment. Demandez à l'opérateur de publier une formule.",
    close: "Fermer",
    payMobileTitle: "Payer par Mobile Money",
    payTitle: "Paiement",
    method: "Méthode",
    phoneLabel: "Numéro de téléphone (chiffres, indicatif pays, sans +)",
    phonePh: "243…",
    reference: "Référence transaction",
    referencePh: "REF / reçu / hash",
    payerContact: "Contact payeur",
    payerContactPh: "Téléphone ou email (optionnel)",
    network: "Réseau",
    paySubmit: "Payer et valider",
    paying: "En attente du paiement…",
    pawapayBlockTitle: "Mobile Money (PawaPay)",
    pawapayBlockLead:
      "Paiement rapide : une demande peut s’afficher sur le téléphone (popup opérateur).",
    alternateBlockTitle: "Autre méthode de paiement",
    alternateBlockLead:
      "TID / virement / cash / carte / crypto : référence soumise, vérification par votre FAI (procédure unifiée).",
    alternateSubmit: "Envoyer la demande",
    payFoot:
      "ⓘ Mobile Money: validation téléphone. Autres méthodes: référence vérifiée par le FAI.",
    daySingular: "jour",
    dayPlural: "jours",
    speed: "Débit",
    type: "Type",
    devices: "Appareils",
    errPhone: "Indiquez un numéro mobile valide (indicatif pays, chiffres uniquement).",
    errRef: "Ajoutez la référence de transaction.",
    noticePhone: "Vérifiez votre téléphone : une demande de validation peut apparaître.",
    noticePostPay:
      "Paiement confirmé. Copiez le jeton ci-dessous, ouvrez le portail client de votre opérateur et définissez un mot de passe avant de quitter cette page.",
    errPayFailed: "Paiement refusé ou annulé. Vous pouvez réessayer.",
    errPayStart: "Impossible de démarrer le paiement.",
    contactTitle: "Contacter votre opérateur",
    contactPhone: "Téléphone",
    contactEmail: "E-mail",
    contactAddress: "Adresse",
    homeShortcut: "Accueil — site public McBuleli",
    mcbuleliPoweredPrefix: "Propulsé par",
    captiveTitle: "Session hotspot (paramètres de redirection)",
    captiveIp: "IP",
    captiveRouter: "Routeur / site",
    captiveMac: "MAC",
    captiveHelp:
      "Ces informations viennent de l’URL (redirection portail captif). Elles sont conservées pendant l’achat."
  },
  en: {
    eyebrow: "Guest Wi‑Fi",
    heroTitle: "Buy an internet pass in seconds.",
    heroLead:
      "Pick a plan, choose a payment method, then activate access.",
    stepPick: "Choose a plan",
    stepPay: "Confirm payment",
    stepOn: "Access enabled",
    catalogLead: "Guest Wi‑Fi catalog with ISP-configured payment methods.",
    wifiBannerAria: "Operator promotional image",
    accessTitle: "Open your ISP catalog",
    accessLead: "Enter the ISP ID (UUID) shared by your provider.",
    ispPh: "ISP ID (UUID from your provider)",
    showPlans: "Show plans",
    postPayTitle: "Create your portal password",
    postPayHelp:
      "On the customer portal page, use First-time setup, paste this token, then set a password so you can sign in later with your phone.",
    openPortal: "Open customer portal",
    continueWifi: "Continue to Wi‑Fi / redirect",
    noPlans: "No public plans yet. Ask your provider to publish a package.",
    close: "Close",
    payMobileTitle: "Pay with Mobile Money",
    payTitle: "Payment",
    method: "Method",
    phoneLabel: "Phone number (digits, country code, no +)",
    phonePh: "243…",
    reference: "Transaction reference",
    referencePh: "REF / receipt / hash",
    payerContact: "Payer contact",
    payerContactPh: "Phone or email (optional)",
    network: "Network",
    paySubmit: "Pay and confirm",
    paying: "Waiting for payment…",
    pawapayBlockTitle: "Mobile Money (PawaPay)",
    pawapayBlockLead: "Fast payment: a prompt may appear on the phone (operator popup).",
    alternateBlockTitle: "Other payment method",
    alternateBlockLead:
      "TID / bank / cash / card / crypto: reference submitted, verified by your ISP (unified flow).",
    alternateSubmit: "Submit request",
    payFoot:
      "ⓘ Mobile Money: confirm on phone. Other methods: reference is reviewed by ISP.",
    daySingular: "day",
    dayPlural: "days",
    speed: "Speed",
    type: "Type",
    devices: "Devices",
    errPhone: "Enter a valid mobile number (country code, digits only).",
    errRef: "Add the transaction reference.",
    noticePhone: "Check your phone—a confirmation prompt may appear.",
    noticePostPay:
      "Payment confirmed. Copy the token below, open your provider's customer portal and set a password before leaving this page.",
    errPayFailed: "Payment declined or cancelled. You can try again.",
    errPayStart: "Could not start payment.",
    contactTitle: "Contact your provider",
    contactPhone: "Phone",
    contactEmail: "Email",
    contactAddress: "Address",
    homeShortcut: "Home — McBuleli public site",
    mcbuleliPoweredPrefix: "Powered by",
    captiveTitle: "Hotspot session (redirect parameters)",
    captiveIp: "IP",
    captiveRouter: "Router / site",
    captiveMac: "MAC",
    captiveHelp: "Taken from the URL (captive portal redirect). Kept through checkout."
  }
};

export function wifiT(lang, key) {
  const k = lang === "en" ? "en" : "fr";
  return STR[k][key] ?? STR.fr[key] ?? key;
}
