const STR = {
  fr: {
    eyebrow: "Wi-Fi invité",
    heroTitle: "Renouveler l'accès",
    heroLead: "Choisissez une offre et payez.",
    stepPick: "Offre",
    stepPay: "Paiement",
    stepOn: "Accès",
    catalogLead: "Offres disponibles",
    wifiBannerAria: "Visuel opérateur",
    accessTitle: "Catalogue",
    accessLead: "Identifiant opérateur (UUID).",
    ispPh: "Identifiant FAI",
    showPlans: "Voir les offres",
    postPayTitle: "Mot de passe portail",
    postPayHelp: "Collez ce jeton sur Première connexion, puis créez un mot de passe.",
    openPortal: "Portail client",
    continueWifi: "Continuer",
    noPlans: "Aucune offre publique.",
    close: "Fermer",
    payMobileTitle: "Mobile Money",
    payTitle: "Paiement",
    method: "Méthode",
    phoneLabel: "Numéro Mobile Money",
    phonePh: "081… ou 243…",
    phoneHint: "",
    reference: "Référence",
    referencePh: "REF / reçu",
    payerContact: "Contact",
    payerContactPh: "Téléphone ou e-mail",
    network: "Réseau",
    paySubmit: "Payer",
    paying: "En attente…",
    pawapayBlockTitle: "Mobile Money",
    pawapayBlockLead: "Confirmez sur votre téléphone.",
    alternateBlockTitle: "Autre méthode",
    alternateBlockLead: "Référence vérifiée par l'opérateur.",
    alternateSubmit: "Envoyer",
    payFoot: "Mobile Money: confirmez sur le téléphone.",
    daySingular: "jour",
    dayPlural: "jours",
    speed: "Débit",
    type: "Type",
    devices: "Appareils",
    renewCta: "Renouveler",
    errPhone: "Numéro invalide (ex. 0812345678).",
    errRef: "Ajoutez la référence.",
    noticePhone: "Vérifiez votre téléphone.",
    noticePostPay: "Paiement ok. Copiez le jeton puis ouvrez le portail.",
    errPayFailed: "Paiement refusé. Réessayez.",
    errPayStart: "Impossible de démarrer le paiement.",
    contactTitle: "Contact",
    contactPhone: "Téléphone",
    contactEmail: "E-mail",
    contactAddress: "Adresse",
    homeShortcut: "Accueil McBuleli",
    mcbuleliPoweredPrefix: "Propulsé par",
    captiveTitle: "Session hotspot",
    captiveIp: "IP",
    captiveRouter: "Routeur",
    captiveMac: "MAC",
    captiveHelp: "Paramètres de redirection."
  },
  en: {
    eyebrow: "Guest Wi-Fi",
    heroTitle: "Renew access",
    heroLead: "Pick a plan and pay.",
    stepPick: "Plan",
    stepPay: "Pay",
    stepOn: "Access",
    catalogLead: "Available plans",
    wifiBannerAria: "Operator image",
    accessTitle: "Catalog",
    accessLead: "Operator ID (UUID).",
    ispPh: "ISP ID",
    showPlans: "Show plans",
    postPayTitle: "Portal password",
    postPayHelp: "Paste this token under First-time setup, then set a password.",
    openPortal: "Customer portal",
    continueWifi: "Continue",
    noPlans: "No public plans.",
    close: "Close",
    payMobileTitle: "Mobile Money",
    payTitle: "Payment",
    method: "Method",
    phoneLabel: "Mobile Money number",
    phonePh: "081… or 243…",
    phoneHint: "",
    reference: "Reference",
    referencePh: "REF / receipt",
    payerContact: "Contact",
    payerContactPh: "Phone or email",
    network: "Network",
    paySubmit: "Pay",
    paying: "Waiting…",
    pawapayBlockTitle: "Mobile Money",
    pawapayBlockLead: "Confirm on your phone.",
    alternateBlockTitle: "Other method",
    alternateBlockLead: "Reference reviewed by your ISP.",
    alternateSubmit: "Submit",
    payFoot: "Mobile Money: confirm on your phone.",
    daySingular: "day",
    dayPlural: "days",
    speed: "Speed",
    type: "Type",
    devices: "Devices",
    renewCta: "Renew",
    errPhone: "Invalid number (e.g. 0812345678).",
    errRef: "Add the transaction reference.",
    noticePhone: "Check your phone.",
    noticePostPay: "Paid. Copy the token, then open the portal.",
    errPayFailed: "Payment declined. Try again.",
    errPayStart: "Could not start payment.",
    contactTitle: "Contact",
    contactPhone: "Phone",
    contactEmail: "Email",
    contactAddress: "Address",
    homeShortcut: "McBuleli home",
    mcbuleliPoweredPrefix: "Powered by",
    captiveTitle: "Hotspot session",
    captiveIp: "IP",
    captiveRouter: "Router",
    captiveMac: "MAC",
    captiveHelp: "Redirect parameters."
  }
};

export function wifiT(lang, key) {
  const k = lang === "en" ? "en" : "fr";
  return STR[k][key] ?? STR.fr[key] ?? key;
}
