const STR = {
  fr: {
    eyebrow: "Wi-Fi invité",
    heroTitle: "Renouveler l'accès",
    heroLead: "Choisissez une offre.",
    stepPick: "Offre",
    stepPay: "Paiement",
    stepOn: "Accès",
    catalogLead: "Offres",
    wifiBannerAria: "Visuel opérateur",
    accessTitle: "Catalogue",
    accessLead: "Identifiant opérateur.",
    ispPh: "Identifiant FAI",
    showPlans: "Voir les offres",
    postPayTitle: "Mot de passe portail",
    postPayHelp: "Collez ce jeton sur Première connexion, puis créez un mot de passe.",
    openPortal: "Portail client",
    continueWifi: "Continuer",
    noPlans: "Aucune offre publique.",
    close: "Fermer",
    payMobileTitle: "Mobile Money",
    payTitle: "Paiement",
    method: "Méthode",
    phoneLabel: "Numéro",
    phonePh: "081… ou 243…",
    phoneHint: "081… devient 24381…",
    reference: "Référence",
    referencePh: "REF / reçu",
    payerContact: "Contact",
    payerContactPh: "Téléphone ou e-mail",
    network: "Réseau",
    paySubmit: "Payer",
    paying: "En attente…",
    pawapayBlockTitle: "Mobile Money",
    pawapayBlockLead: "Confirmez sur votre téléphone.",
    payTabMm: "Mobile Money",
    payTabMcbuleli: "Code McBuleli",
    payTabWifiVoucher: "Voucher Wi‑Fi",
    payTabVoucher: "Code McBuleli",
    voucherCodeLabel: "Code McBuleli",
    voucherCodePh: "VCH-… ou MB…",
    voucherPasswordLabel: "Mot de passe portail",
    voucherPasswordPh: "Min. 6 caractères",
    voucherSubmit: "Activer",
    voucherBusy: "Activation…",
    voucherOk: "Code activé. Redirection…",
    errVoucherCode: "Entrez le code.",
    errVoucherPassword: "Mot de passe requis (min. 6 caractères).",
    wifiVoucherTitle: "Voucher Wi‑Fi",
    wifiVoucherHelp: "",
    wifiVoucherCodePh: "Code (ex. MB12FH25KQ)",
    wifiVoucherHint: "Sur la page Wi‑Fi du routeur.",
    wifiVoucherActivate: "Activer",
    wifiVoucherReady: "Code prêt - entrez-le sur la page Wi‑Fi.",
    errWifiVoucherCode: "Entrez le code voucher.",
    alternateBlockTitle: "Autre méthode",
    alternateBlockLead: "Référence vérifiée par l'opérateur.",
    alternateSubmit: "Envoyer",
    payFoot: "",
    daySingular: "jour",
    dayPlural: "jours",
    speed: "Débit",
    type: "Type",
    devices: "appareils",
    renewCta: "Choisir",
    errPhone: "Numéro invalide (ex. 0812345678).",
    errRef: "Ajoutez la référence.",
    noticePhone: "Vérifiez votre téléphone.",
    noticeManualPending: "Référence envoyée. En attente de validation opérateur…",
    noticeRedirecting: "Paiement ok. Redirection…",
    noticePostPay: "Paiement ok. Copiez le jeton puis ouvrez le portail.",
    errPayFailed: "Paiement refusé. Réessayez.",
    errPayStart: "Impossible de démarrer le paiement.",
    contactTitle: "Contact",
    contactPhone: "Téléphone",
    contactEmail: "E-mail",
    contactAddress: "Adresse",
    homeShortcut: "Accueil",
    mcbuleliPoweredPrefix: "Propulsé par",
    captiveTitle: "Session hotspot",
    captiveIp: "IP",
    captiveRouter: "Routeur",
    captiveMac: "MAC",
    captiveHelp: ""
  },
  en: {
    eyebrow: "Guest Wi-Fi",
    heroTitle: "Renew access",
    heroLead: "Choose a plan.",
    stepPick: "Plan",
    stepPay: "Pay",
    stepOn: "Access",
    catalogLead: "Plans",
    wifiBannerAria: "Operator image",
    accessTitle: "Catalog",
    accessLead: "Operator ID.",
    ispPh: "ISP ID",
    showPlans: "Show plans",
    postPayTitle: "Portal password",
    postPayHelp: "Paste this token under First-time setup, then set a password.",
    openPortal: "Customer portal",
    continueWifi: "Continue",
    noPlans: "No public plans.",
    close: "Close",
    payMobileTitle: "Mobile Money",
    payTitle: "Payment",
    method: "Method",
    phoneLabel: "Number",
    phonePh: "081… or 243…",
    phoneHint: "081… becomes 24381…",
    reference: "Reference",
    referencePh: "REF / receipt",
    payerContact: "Contact",
    payerContactPh: "Phone or email",
    network: "Network",
    paySubmit: "Pay",
    paying: "Waiting…",
    pawapayBlockTitle: "Mobile Money",
    pawapayBlockLead: "Confirm on your phone.",
    payTabMm: "Mobile Money",
    payTabMcbuleli: "McBuleli code",
    payTabWifiVoucher: "Wi‑Fi voucher",
    payTabVoucher: "McBuleli code",
    voucherCodeLabel: "McBuleli code",
    voucherCodePh: "VCH-… or MB…",
    voucherPasswordLabel: "Portal password",
    voucherPasswordPh: "Min. 6 characters",
    voucherSubmit: "Activate",
    voucherBusy: "Activating…",
    voucherOk: "Code activated. Redirecting…",
    errVoucherCode: "Enter the code.",
    errVoucherPassword: "Password required (min. 6 characters).",
    wifiVoucherTitle: "Wi‑Fi voucher",
    wifiVoucherHelp: "",
    wifiVoucherCodePh: "Code (e.g. MB12FH25KQ)",
    wifiVoucherHint: "On the router Wi‑Fi login page.",
    wifiVoucherActivate: "Activate",
    wifiVoucherReady: "Code ready - enter it on the Wi‑Fi login page.",
    errWifiVoucherCode: "Enter the voucher code.",
    alternateBlockTitle: "Other method",
    alternateBlockLead: "Reference reviewed by your ISP.",
    alternateSubmit: "Submit",
    payFoot: "",
    daySingular: "day",
    dayPlural: "days",
    speed: "Speed",
    type: "Type",
    devices: "devices",
    renewCta: "Select",
    errPhone: "Invalid number (e.g. 0812345678).",
    errRef: "Add the transaction reference.",
    noticePhone: "Check your phone.",
    noticeManualPending: "Reference sent. Waiting for operator validation…",
    noticeRedirecting: "Paid. Redirecting…",
    noticePostPay: "Paid. Copy the token, then open the portal.",
    errPayFailed: "Payment declined. Try again.",
    errPayStart: "Could not start payment.",
    contactTitle: "Contact",
    contactPhone: "Phone",
    contactEmail: "Email",
    contactAddress: "Address",
    homeShortcut: "Home",
    mcbuleliPoweredPrefix: "Powered by",
    captiveTitle: "Hotspot session",
    captiveIp: "IP",
    captiveRouter: "Router",
    captiveMac: "MAC",
    captiveHelp: ""
  }
};

export function wifiT(lang, key) {
  const k = lang === "en" ? "en" : "fr";
  return STR[k][key] ?? STR.fr[key] ?? key;
}
